"""
Growth OS Phase 1 -- AI SEO Engine.

Turns XFINLAB's already-live per-ticker SEO landing pages (see aapl.html,
built across tasks #453-502) into a repeatable, admin-controlled pipeline
instead of one-off hand-written HTML. Three pieces:

1. list_existing_pages() -- read-only glob of the ticker/comparison pages
   already on disk (safe: never writes anything).
2. suggest_candidates() -- cross-references js/autocomplete.js's ~400-asset
   universe (the same dataset used site-wide for ticker search) against
   pages that already exist, returning assets that don't have a landing
   page yet, ranked by the `popularity` score autocomplete.js already
   carries per asset.
3. create_ticker_page() -- renders a new page from the same template
   family as aapl.html (dark theme, FAQPage+BreadcrumbList JSON-LD, live
   price/trend fetch, related-assets cross-links), writes it, and appends
   it to sitemap.xml. Never overwrites an existing file.

Nothing here runs automatically on a schedule -- every generation is
triggered by an explicit admin action (api/admin.py's /admin/seo/*
endpoints), per the user's own requirement: "後台加入可控制" (build it,
but keep it admin-controllable rather than silently autonomous).
"""
import os
import re
import glob
import json
from datetime import date

REPO_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SITEMAP_PATH = os.path.join(REPO_ROOT, "sitemap.xml")
AUTOCOMPLETE_JS_PATH = os.path.join(REPO_ROOT, "js", "autocomplete.js")
REGISTRY_PATH = os.path.join(REPO_ROOT, "reports", "seo_pages_registry.json")

# Core site pages that legitimately live in the repo root alongside the
# ticker pages. list_existing_pages() excludes these so it never
# misreports normal site pages as "SEO ticker pages" generated by this
# engine.
_CORE_PAGES = {
    "index.html", "home.html", "login.html", "register.html", "dashboard.html",
    "pricing.html", "terms.html", "privacy.html", "refund.html", "risk-warning.html",
    "api-terms.html", "chat.html", "screener.html", "anomaly.html", "portfolio.html",
    "pairs-scan.html", "probability-scan.html", "company-compare.html",
    "news-denoise.html", "chart-analysis.html", "ai-analysis.html", "stress-lab.html",
    "tools.html", "free-signals.html", "admin.html", "forgot-password.html",
    "reset-password.html", "verify-email.html", "intelligence-api.html", "news.html",
    "nasdaq.html", "pe-calculator.html", "dcf-calculator.html",
    "position-size-calculator.html", "compound-interest-calculator.html",
    "widgets.html",
}


def _registry():
    if not os.path.exists(REGISTRY_PATH):
        return {}
    try:
        with open(REGISTRY_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _save_registry(reg):
    os.makedirs(os.path.dirname(REGISTRY_PATH), exist_ok=True)
    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        json.dump(reg, f, ensure_ascii=False, indent=2)


def list_existing_pages():
    """Read-only: every *.html in the repo root that looks like a
    ticker/comparison SEO page (i.e. not one of the core site pages)."""
    pages = []
    for path in sorted(glob.glob(os.path.join(REPO_ROOT, "*.html"))):
        name = os.path.basename(path)
        if name in _CORE_PAGES:
            continue
        pages.append(name[:-5])  # strip ".html"
    reg = _registry()
    return {
        "count": len(pages),
        "pages": pages,
        "generated_by_engine": len(reg),
    }


def _slugify(ticker):
    return re.sub(r"[^a-z0-9\-]", "", ticker.lower())


def _parse_autocomplete_assets():
    """Best-effort regex extraction of {symbol,name,type,popularity} from
    js/autocomplete.js's ASSETS array -- reuses the site's existing ticker
    universe rather than maintaining a second registry. Not a full JS
    parser; tolerant of extra fields per object (aliases, logo, etc.)."""
    if not os.path.exists(AUTOCOMPLETE_JS_PATH):
        return []
    text = open(AUTOCOMPLETE_JS_PATH, encoding="utf-8").read()
    pattern = re.compile(
        r'\{symbol:"(?P<symbol>[^"]+)",name:"(?P<name>[^"]+)",type:"(?P<type>[^"]+)"'
        r'[^}]*?popularity:(?P<popularity>\d+)'
    )
    out = []
    seen = set()
    for m in pattern.finditer(text):
        sym = m.group("symbol")
        if sym in seen:
            continue
        seen.add(sym)
        out.append({
            "symbol": sym,
            "name": m.group("name"),
            "type": m.group("type"),
            "popularity": int(m.group("popularity")),
        })
    return out


def suggest_candidates(limit=30):
    """Assets from the site's own autocomplete universe that don't have a
    landing page yet, ranked by popularity (most-searched-for first). This
    is the "AI" part of the AI SEO Engine in the sense that matters for a
    one-person team: it tells you what to build next instead of guessing."""
    existing = {p.lower() for p in list_existing_pages()["pages"]}
    assets = _parse_autocomplete_assets()
    out = [a for a in assets if _slugify(a["symbol"]) not in existing]
    out.sort(key=lambda a: -a["popularity"])
    return out[:limit]


_CATEGORY_LABEL = {
    "stock": "Stock", "crypto": "Cryptocurrency", "forex": "Forex Pair",
    "etf": "ETF", "index": "Index", "commodity": "Commodity", "bond": "Bond",
}


def generate_page(ticker, company_name, category="stock", related=None):
    """Renders one ticker landing page as an HTML string, matching the
    established aapl.html template (dark theme, live price/trend fetch,
    FAQPage+BreadcrumbList JSON-LD, related-assets section, risk
    disclaimer, cookie-consent + anti-scrape scripts)."""
    slug = _slugify(ticker)
    ticker_up = ticker.upper()
    cat_label = _CATEGORY_LABEL.get(category, "Asset")
    related = related or []
    related_links = "\n".join(
        f'<a href="/{_slugify(r)}.html">{r.upper()}</a>' for r in related
    ) or '<a href="/tools.html">Explore more tools</a>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<link rel="icon" type="image/png" href="/img/logo-mark.png">
<link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
<link rel="shortcut icon" href="/img/favicon.ico">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{ticker_up} {cat_label} Analysis 2026 - XFINLAB AI</title>
<link rel="canonical" href="https://www.xfinlab.com/{slug}.html">
<meta name="robots" content="index, follow">
<meta name="description" content="AI-powered {ticker_up} ({company_name}) analysis. Get real-time price, risk assessment, and investment insight powered by XFINLAB Intelligence.">
<meta name="keywords" content="{ticker_up}, {ticker_up} {category}, {ticker_up} analysis, {company_name}, {category} analysis, AI investment, XFINLAB">
<meta property="og:title" content="{ticker_up} {cat_label} Analysis - XFINLAB AI">
<meta property="og:description" content="Get AI-powered {ticker_up} analysis: real-time price, risk assessment, and investment insight — free on XFINLAB.">
<meta property="og:url" content="https://www.xfinlab.com/{slug}.html">
<style>
body{{font-family:'Inter',sans-serif;background:#080c14;color:#e2e8f0;margin:0;padding:0}}
nav{{background:#0d1525;padding:16px 32px;border-bottom:1px solid #1e2d45}}
.breadcrumb{{font-size:0.78rem;color:#64748b;margin-bottom:16px}}
.breadcrumb a{{color:#64748b;text-decoration:none}}
.breadcrumb a:hover{{color:#00d4ff}}
.related a{{display:inline-block;color:#00d4ff;text-decoration:none;background:#0d1525;border:1px solid #1e2d45;border-radius:8px;padding:8px 14px;margin:4px 6px 4px 0;font-size:0.85rem}}
.related a:hover{{border-color:#00d4ff}}
.brand{{color:#00d4ff;font-weight:700;font-size:1.1rem;text-decoration:none}}
main{{max-width:900px;margin:0 auto;padding:40px 24px}}
h1{{font-size:2rem;color:#fff;margin-bottom:8px}}
.subtitle{{color:#64748b;margin-bottom:32px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin-bottom:32px}}
.card{{background:#0d1525;border:1px solid #1e2d45;border-radius:12px;padding:20px}}
.label{{font-size:0.7rem;text-transform:uppercase;letter-spacing:0.1em;color:#64748b;margin-bottom:8px}}
.value{{font-size:1.8rem;font-weight:700;color:#00d4ff}}
.section{{background:#0d1525;border:1px solid #1e2d45;border-radius:12px;padding:24px;margin-bottom:20px}}
h2{{color:#94a3b8;font-size:0.8rem;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:12px}}
p{{color:#cbd5e1;line-height:1.8}}
.cta{{background:#00d4ff;color:#000;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:700;display:inline-block;margin-top:20px}}
footer{{text-align:center;padding:32px;color:#64748b;font-size:0.8rem;border-top:1px solid #1e2d45;margin-top:40px}}
</style>
<script type="application/ld+json">
[
  {{
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {{
        "@type": "Question",
        "name": "Is this financial advice?",
        "acceptedAnswer": {{
          "@type": "Answer",
          "text": "No. XFINLAB's analysis is for informational purposes only and does not constitute financial advice. Always conduct your own research and consult a qualified financial advisor before making investment decisions."
        }}
      }},
      {{
        "@type": "Question",
        "name": "How often is the {ticker_up} data updated?",
        "acceptedAnswer": {{
          "@type": "Answer",
          "text": "Price and trend figures shown on this page are fetched live from market data providers each time the page loads."
        }}
      }},
      {{
        "@type": "Question",
        "name": "What does XFINLAB's full AI analysis include?",
        "acceptedAnswer": {{
          "@type": "Answer",
          "text": "XFINLAB's full platform layers on news sentiment, technical indicators, risk scoring, and a 0-100 investment score, free to try with no credit card required."
        }}
      }}
    ]
  }},
  {{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://www.xfinlab.com/" }},
      {{ "@type": "ListItem", "position": 2, "name": "Free Tools", "item": "https://www.xfinlab.com/tools.html" }},
      {{ "@type": "ListItem", "position": 3, "name": "{ticker_up}", "item": "https://www.xfinlab.com/{slug}.html" }}
    ]
  }}
]
</script>
</head>
<body>
<nav><a href="/" class="brand"><img src="/img/logo-mark.png" alt="XFINLAB" style="height:1.3em;width:auto;vertical-align:middle;margin-right:6px">XFINLAB</a></nav>
<main>
<div class="breadcrumb"><a href="/">Home</a> &rsaquo; <a href="/tools.html">Free Tools</a> &rsaquo; {ticker_up}</div>
<h1>{ticker_up} — {company_name}</h1>
<p class="subtitle">AI Investment Analysis · Live Data</p>

<div class="grid">
  <div class="card"><div class="label">Price</div><div class="value" id="priceValue">—</div></div>
  <div class="card"><div class="label">Trend</div><div class="value" id="trendValue" style="font-size:1.1rem">—</div></div>
</div>

<div class="section">
<h2>Full AI Score, Risk &amp; Rating for {ticker_up}</h2>
<p>XFINLAB's full platform generates a complete AI investment score, risk assessment, and rating for {ticker_up} from real market data, news sentiment, and technical indicators — free, no credit card required.</p>
</div>

<div class="section">
<h2>About {company_name}</h2>
<p>{company_name} ({ticker_up}) is analyzed by XFINLAB's AI Investment Intelligence platform. Our system evaluates market data, news sentiment, technical indicators, and risk factors to generate comprehensive investment insights.</p>
</div>

<div class="section">
<h2>AI Analysis Methodology</h2>
<p>XFINLAB uses a multi-layer analysis pipeline combining market data scoring, news sentiment analysis, strategy evaluation, and risk assessment to generate a final investment score from 0-100.</p>
</div>

<div class="section">
<h2>Frequently Asked Questions</h2>
<p><strong>Is this financial advice?</strong> No. XFINLAB's analysis is for informational purposes only and does not constitute financial advice. Always conduct your own research and consult a qualified financial advisor before making investment decisions.</p>
<p><strong>How often is the {ticker_up} data updated?</strong> Price and trend figures shown above are fetched live from market data providers each time this page loads.</p>
<p><strong>What does the full AI analysis include?</strong> XFINLAB's full platform layers on news sentiment, technical indicators, risk scoring, and a 0-100 investment score — free to try, no credit card required.</p>
</div>

<div class="section related">
<h2>Related</h2>
{related_links}
</div>

<div class="ad-slot" data-slot="ticker-page-mid" style="margin:20px 0;min-height:0"></div>

<div class="section">
<h2>Risk Disclaimer</h2>
<p>This analysis is for informational purposes only and does not constitute financial advice. Always conduct your own research and consult a qualified financial advisor before making investment decisions.</p>
</div>

<a href="https://xfinlab.com" class="cta">Get Full AI Analysis →</a>
</main>
<footer>© 2026 XFINLAB — AI Investment Intelligence Platform</footer>
<script>
(function() {{
  fetch('https://api.xfinlab.com/api/market/{ticker_up}')
    .then(r => r.json())
    .then(data => {{
      if (data && !data.error && data.price) {{
        document.getElementById('priceValue').textContent = '$' + data.price.toLocaleString();
        const trendMap = {{ bullish: '📈 Bullish', bearish: '📉 Bearish' }};
        document.getElementById('trendValue').textContent = trendMap[data.trend] || '—';
      }} else {{
        document.getElementById('priceValue').textContent = 'N/A';
        document.getElementById('trendValue').textContent = 'N/A';
      }}
    }})
    .catch(() => {{
      document.getElementById('priceValue').textContent = 'N/A';
      document.getElementById('trendValue').textContent = 'N/A';
    }});
}})();
</script>
<script src="js/cookie-consent.js"></script>
<script src="js/anti-scrape.js"></script>
<script src="js/ads.js"></script>
<script src="js/support-widget.js"></script>
</body>
</html>
"""


def add_to_sitemap(slug, priority="0.6", changefreq="weekly"):
    """Appends one <url> entry before </urlset>. Idempotent -- skips (and
    returns False) if the URL is already present, so it's safe to call
    again for a page that already has a sitemap entry."""
    url = f"https://www.xfinlab.com/{slug}.html"
    if not os.path.exists(SITEMAP_PATH):
        return False
    text = open(SITEMAP_PATH, encoding="utf-8").read()
    if url in text:
        return False
    entry = f"""  <url>
    <loc>{url}</loc>
    <changefreq>{changefreq}</changefreq>
    <priority>{priority}</priority>
  </url>
</urlset>"""
    text = text.replace("</urlset>", entry)
    with open(SITEMAP_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    return True


def create_ticker_page(ticker, company_name, category="stock", related=None, force=False):
    """Full pipeline: validate slug -> render -> write file -> add to
    sitemap -> record in registry. Refuses to overwrite an existing file
    unless force=True (force is intentionally not exposed via the admin
    API -- it exists only for local re-generation during development, so
    a mistyped admin request can never clobber a live page)."""
    slug = _slugify(ticker)
    if not slug or not re.match(r"^[a-z0-9\-]{1,15}$", slug):
        raise ValueError(f"Invalid ticker slug: {ticker!r}")
    path = os.path.join(REPO_ROOT, f"{slug}.html")
    if os.path.exists(path) and not force:
        raise FileExistsError(f"{slug}.html already exists")

    html = generate_page(ticker, company_name, category, related)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    add_to_sitemap(slug)

    reg = _registry()
    reg[slug] = {
        "ticker": ticker.upper(),
        "company_name": company_name,
        "category": category,
        "created": date.today().isoformat(),
    }
    _save_registry(reg)
    return {"slug": slug, "path": f"{slug}.html", "sitemap_added": True}
